export type InterestCategory = {
  id: string;
  label: string;
  items: string[];
};

/** Catalogue enrichi des centres d’intérêt (sélection multiple). */
export const INTEREST_CATEGORIES: InterestCategory[] = [
  {
    id: 'culture',
    label: 'Culture & médias',
    items: [
      'Cinéma',
      'Séries',
      'Lecture',
      'BD & mangas',
      'Théâtre',
      'Musées',
      'Podcasts',
      'Documentaires',
      'Écriture',
      'Photographie',
      'Art',
      'Histoire',
      'Philosophie',
    ],
  },
  {
    id: 'music',
    label: 'Musique',
    items: [
      'Musique',
      'Concerts',
      'Festivals',
      'DJ & électro',
      'Chant',
      'Guitare',
      'Piano',
      'Jazz',
      'Rock',
      'Rap & hip-hop',
      'Classique',
      'Karaoké',
    ],
  },
  {
    id: 'sport',
    label: 'Sport & outdoor',
    items: [
      'Sport',
      'Fitness',
      'Course à pied',
      'Randonnée',
      'Vélo',
      'Natation',
      'Yoga',
      'Pilates',
      'Escalade',
      'Ski & snowboard',
      'Surf',
      'Tennis',
      'Football',
      'Basketball',
      'Arts martiaux',
      'Danse',
      'Paddle',
      'Camping',
    ],
  },
  {
    id: 'food',
    label: 'Gastronomie',
    items: [
      'Cuisine',
      'Pâtisserie',
      'Restaurants',
      'Vin & œnologie',
      'Café & specialty coffee',
      'Brunch',
      'Street food',
      'Végétarien',
      'Vegan',
      'Cocktails',
      'Fromages',
      'Barbecue',
    ],
  },
  {
    id: 'travel',
    label: 'Voyage & découverte',
    items: [
      'Voyage',
      'Road trips',
      'Week-ends improvisés',
      'Van life',
      'Plages',
      'Montagne',
      'City trips',
      'Langues étrangères',
      'Cultures du monde',
      'Nature',
    ],
  },
  {
    id: 'games',
    label: 'Jeux & tech',
    items: [
      'Gaming',
      'Jeux de société',
      'Échecs',
      'Escape games',
      'Technologie',
      'IA & innovation',
      'Sciences',
      'Astronomie',
      'DIY & bricolage',
      'High-tech',
    ],
  },
  {
    id: 'lifestyle',
    label: 'Lifestyle & bien-être',
    items: [
      'Méditation',
      'Bien-être',
      'Spa & sauna',
      'Mode',
      'Décoration',
      'Jardinage',
      'Animaux',
      'Chiens',
      'Chats',
      'Écologie',
      'Zéro déchet',
      'Volontariat',
    ],
  },
  {
    id: 'social',
    label: 'Social & sorties',
    items: [
      'Apéros entre amis',
      'Soirées',
      'Bars & pubs',
      'Humoristes',
      'Spectacles',
      'Marchés',
      'Brocante & vide-greniers',
      'Bénévolat',
      'Networking',
      'Stand-up',
    ],
  },
  {
    id: 'creative',
    label: 'Créatif & manuel',
    items: [
      'Dessin',
      'Peinture',
      'Couture',
      'Tricot',
      'Céramique',
      'Calligraphie',
      'Bricolage',
      'Menuiserie',
      'Scrapbooking',
      'Création de contenu',
    ],
  },
  {
    id: 'mind',
    label: 'Esprit & apprentissage',
    items: [
      'Développement personnel',
      'Psychologie',
      'Spiritualité',
      'Astrologie',
      'Politique',
      'Actualité',
      'Entrepreneuriat',
      'Finance personnelle',
      'Investissement',
      'Formation continue',
    ],
  },
];

export const ALL_SUGGESTED_INTERESTS: string[] = Array.from(
  new Set(INTEREST_CATEGORIES.flatMap((category) => category.items))
);

export const MIN_INTERESTS = 3;
